version: '3'
services:
  pglineage:
    container_name: pglineage
    image: pglineage
    restart: always
    build: .
    tty: true
    volumes:
      - ./resource:/usr/local/pglineage/resource
      - ./output:/usr/local/pglineage/output
