# muti join, nest
case_subquery_1 = (
    "SELECT "
    "    tbl1.col1, "
    "    tbl2.col2, "
    "    tbl3.col3 "
    "FROM "
    "    ( "
    "        SELECT "
    "            col1, "
    "            col2 "
    "        FROM "
    "            table1 "
    "    ) AS tbl1 "
    "    INNER JOIN ( "
    "        SELECT "
    "            col1, "
    "            col2, "
    "            col3 "
    "        FROM "
    "            table2 "
    "    ) AS tbl2 ON tbl1.col2 = tbl2.col2 "
    "    INNER JOIN ( "
    "        SELECT "
    "            col1, "
    "            col2, "
    "            col3 "
    "        FROM "
    "            table3 "
    "        WHERE "
    "            EXISTS ( "
    "                SELECT "
    "                    1 "
    "                FROM "
    "                    table3, "
    "                    table4 "
    "                WHERE "
    "                    table3.col4 = table4.col4 "
    "            ) "
    "    ) AS tbl3 ON tbl2.col3 = tbl3.col3; "
)
